### ISSUE TITLE
Error with KonopkaControls Components

### ISSUE THREAD

**Issue by ClubACNews** [hydrobyte/McSimpleProp#1]
Hi,
If I use your source with the KonopkaControls-290-7.0 for Delphi, I've an error of this line : 
`fMcSimpleProp := TMcSimpleProp.Create(RzTreeView, RzPageControl);`

E2250 : Aucune version surchargée de "Create' ne peut être appelée avec ces arguments.

How to change the code ?
Thanks
François

**Comment by hydrobyte** [comment]
Hi, 
I don't have Konopka Controls installed here, but you might check if `TRzTreeView` and `TRzPageControl` are descendants from `TTreeView` and `TPageControl`, respectively.

Maybe something like this:

```pascal
var
  aTreeView: TTreeView;
  aPageControl: TPageControl;
begin
  aTreeView := RzTreeView as TTreeView;
  aPageControl := RzPageControl as TPageControl;
  // ...
  fMcSimpleProp := TMcSimpleProp.Create(aTreeView, aPageControl);

**Comment by ClubACNews** [comment]
Hi,
I've find the solution.
You must déclare the 2 components in uses and replace by TRzTreeView, TRzPagecontrol and TrzTabSheet.
It's OK
Thanks
François
